version: "3.9" #We specify a version for Compose. Make sure Compose is compatible with Docker
services:
  client:
    # stdin_open: true
    # build:
    #   context: .
    #   dockerfile: Dockerfile #The client service requires a docker file to be specified. For development, we’re going to use the Dockerfile.dev file.
    image: "testJenk/ui"
    ports:
      - "3000:5173" #Next, we map the port 3000 to Docker. The React application runs on port 3000, so we need to tell Docker which port to expose for our application.
    volumes:
      - "/app/node_modules"
      - "./:/app"